### ISSUE TITLE
修正ありがとうございます。

### ISSUE THREAD

**Issue by linel-ine** [n-fukuju/vertical-writing-vsce#3]
VSマーケットでレビューした者です。
早々にご対応いただきありがとうございます。

ちなみにレビューではなく通常の編集ウインドウを縦書きにするのは難しいんどえしょうか？

**Comment by n-fukuju** [comment]
@linel-ine 
標準テキストエディタ（通常の編集ウインドウ）を縦書きにできるかどうかは本拡張を開発する以前に簡単に調査しましたが、おそらく拡張機能から標準テキストエディタを変更することはできません。

代わりに、[カスタムエディタAPI](https://code.visualstudio.com/api/extension-guides/custom-editors)を使用すればエディタを独自実装できますが、これはHTML等を使用して新規にエディタを実装するもので、開発の負荷が非常に高いです。

本拡張では代替案として推敲のための使用をメインに想定して縦書きプレビューを実装しています。

以上、回答としましては、編集ウインドウを縦書きにすることは難しいです。

**Comment by linel-ine** [comment]
早々なご回答ありがとうございます。
言われてみれば確かにそうですね。
お手を煩わせ大変申し訳ございません！
