### ISSUE TITLE
Opinion about requesting VSCode to support vertical editing?

### ISSUE THREAD

**Issue by nobodxbodon** [n-fukuju/vertical-writing-vsce#4]
Hi, FYI there's [a feature request](https://github.com/microsoft/vscode/issues/152005) to support vertical editing, and I found your extension with similar effects so I put it as reference there.

Any thoughts or suggestion is more than welcome.

**Comment by n-fukuju** [comment]
Thank you for your message.
I can't wait for VSCode update. 👍
